### ISSUE TITLE
 Authentication failed. MFA required. (10001)

### ISSUE THREAD

**Issue by ysrinivasarao** [microsoft/Partner-Center-DotNet-Samples#59]
Partner Exception:
Error Category: Unauthorized
Service Error Payload: null
Context: Request Id: f604e6a0-96be-4c53-bc57-b877e672ca77, Correlation Id: 71bb26c8-89f4-474d-882d-e35ac853283e, Locale: en-US
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Authentication failed. MFA required. (10001)
   at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation)
   at Microsoft.Store.PartnerCenter.Samples.Customers.GetPagedCustomers.RunScenario() in C:\sdk\SdkSamples\Customers\GetPagedCustomers.cs:line 42
   at Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\sdk\SdkSamples\BasePartnerScenario.cs:line 78

**Comment by PulcoO** [comment]
Hello,

I have exactly the same issue. Did you manage to solve it?

**Comment by ysrinivasarao** [comment]
No, I couldn't figure it out... 

Best Regards,Srinivasa Rao YadlapalliMobile: 732 476 7034
 

    On Tuesday, January 5, 2021, 04:02:42 AM EST, PulcoOx <notifications@github.com> wrote:  
 
 


Hello,

I have exactly the same issue. Did you manage to solve it?

**Comment by attahameed** [comment]
I am facing the same issue, and so far no colution.
However, one article suggest that you turn off MS security default in Azure AD and then you may get it to work
https://docs.microsoft.com/en-us/partner-center/partner-security-requirements

**Comment by robnetgithub** [comment]
As described in the error, you just need to authenticate with an account that has MFA enabled. Otherwise, if you authenticate using an account with MFA not enabled, it may say 'Authenticated!' in the console app, but you will get that error when you try to use any of the sample functions. Check your account security settings.
