### ISSUE TITLE
Create Customer scenario

### ISSUE THREAD

**Issue by tnlthanzeel** [microsoft/Partner-Center-DotNet-Samples#73]
tried creating a customer and i get this error

Create a new customer
--------------------------------------------------------------------------------

New customer Information
------------------------------------------------------------------------------------------
    CompanyProfile:
        Domain: SampleApplication130339732.onmicrosoft.com
        Attributes:
            ObjectType: CustomerCompanyProfile
    BillingProfile:
        Email: gena@relecloud2.com
        Culture: en-US
        Language: en
        CompanyName: Relecloud130339732
        DefaultAddress:
            Country: US
            City: Redmond
            State: WA
            AddressLine1: 4567 Main Street
            PostalCode: 98052
            FirstName: Gena
            MiddleName: MiddleName
            LastName: Soto
            PhoneNumber: 4255550101
        Attributes:
            ObjectType: CustomerBillingProfile
    RelationshipToPartner: Unknown
    Attributes:
        ObjectType: Customer
------------------------------------------------------------------------------------------

Creating customer.

**Partner Exception:
Error Category: Forbidden
Service Error Payload:
Error code: 600006
Error message: The requested action is not allowed

Context: Request Id: cc3d6e10-a6d9-475d-92cb-39412f643fc3, Correlation Id: e7fa0a90-f5fe-40ff-a1cf-afc0eb903b6f, Locale: en-US
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: The requested action is not allowed
   at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation)
   at Microsoft.Store.PartnerCenter.Samples.Customers.CreateCustomer.RunScenario() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\Customers\CreateCustomer.cs:line 65
   at Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\BasePartnerScenario.cs:line 78**

please help

**Comment by RommelWZ** [comment]
> tried creating a customer and i get this error
> 
> ## Create a new customer
> ## New customer Information
> ```
> CompanyProfile:
>     Domain: SampleApplication130339732.onmicrosoft.com
>     Attributes:
>         ObjectType: CustomerCompanyProfile
> BillingProfile:
>     Email: gena@relecloud2.com
>     Culture: en-US
>     Language: en
>     CompanyName: Relecloud130339732
>     DefaultAddress:
>         Country: US
>         City: Redmond
>         State: WA
>         AddressLine1: 4567 Main Street
>         PostalCode: 98052
>         FirstName: Gena
>         MiddleName: MiddleName
>         LastName: Soto
>         PhoneNumber: 4255550101
>     Attributes:
>         ObjectType: CustomerBillingProfile
> RelationshipToPartner: Unknown
> Attributes:
>     ObjectType: Customer
> ```
> 
> Creating customer.
> 
> **Partner Exception: Error Category: Forbidden Service Error Payload: Error code: 600006 Error message: The requested action is not allowed
> 
> Context: Request Id: cc3d6e10-a6d9-475d-92cb-39412f643fc3, Correlation Id: e7fa0a90-f5fe-40ff-a1cf-afc0eb903b6f, Locale: en-US Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: The requested action is not allowed at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation) at Microsoft.Store.PartnerCenter.Samples.Customers.CreateCustomer.RunScenario() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\Customers\CreateCustomer.cs:line 65 at Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\BasePartnerScenario.cs:line 78**
> 
> please help

Have you fixed the Forbidden error?

**Comment by rohitpandit18** [comment]
Please give  the solution of this problem

**Comment by rohitpandit18** [comment]
> > tried creating a customer and i get this error
> > ## Create a new customer
> > ## New customer Information
> > ```
> > CompanyProfile:
> >     Domain: SampleApplication130339732.onmicrosoft.com
> >     Attributes:
> >         ObjectType: CustomerCompanyProfile
> > BillingProfile:
> >     Email: gena@relecloud2.com
> >     Culture: en-US
> >     Language: en
> >     CompanyName: Relecloud130339732
> >     DefaultAddress:
> >         Country: US
> >         City: Redmond
> >         State: WA
> >         AddressLine1: 4567 Main Street
> >         PostalCode: 98052
> >         FirstName: Gena
> >         MiddleName: MiddleName
> >         LastName: Soto
> >         PhoneNumber: 4255550101
> >     Attributes:
> >         ObjectType: CustomerBillingProfile
> > RelationshipToPartner: Unknown
> > Attributes:
> >     ObjectType: Customer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Creating customer.
> > **Partner Exception: Error Category: Forbidden Service Error Payload: Error code: 600006 Error message: The requested action is not allowed
> > Context: Request Id: cc3d6e10-a6d9-475d-92cb-39412f643fc3, Correlation Id: e7fa0a90-f5fe-40ff-a1cf-afc0eb903b6f, Locale: en-US Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: The requested action is not allowed at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation) at Microsoft.Store.PartnerCenter.Samples.Customers.CreateCustomer.RunScenario() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\Customers\CreateCustomer.cs:line 65 at Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Projects\new\Partner-Center-DotNet-Samples\sdk\SdkSamples\BasePartnerScenario.cs:line 78**
> > please help
> 
> @tnlthanzeel Have you fixed the Forbidden error?

Please give the solution of this Problem

**Comment by mikaelz** [comment]
have the same issue and don't know why. Don't understand why `The requested action is not allowed` ? Created multiple other customers without issue previously

**Comment by rohitpandit18** [comment]
I was facing the same issue but now it is resolved. Please check name and
data properly and there is limitation of everything you have to check and
then fill every detail. if still you got unsuccessful then i will send you
the correct code for this
