### ISSUE TITLE
Azure Vault Exception

### ISSUE THREAD

**Issue by SalmanMukhtar** [Microsoft/Partner-Center-DotNet-Samples#8]
Getting following exception while running CSP application.

===================== Partner center  API calls ============================
**Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'NotFound'**
   at Microsoft.Azure.KeyVault.KeyVaultClient.<GetSecretWithHttpMessagesAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<GetSecretAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CPVApplication.Utilities.KeyVaultProvider.<GetSecretAsync>d__3.MoveNext() in C:\Users\salman\Desktop\SAM - Azure\Partner-Center-DotNet-Samples-dev-samples-update\secure-app-model\keyvault\CSPApplication\Utilities\KeyVaultProvider.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CPVApplication.Program.<LoginToPartnerCenter>d__4.MoveNext() in C:\Users\salman\Desktop\SAM - Azure\Partner-Center-DotNet-Samples-dev-samples-update\secure-app-model\keyvault\CSPApplication\Program.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CPVApplication.Program.<GetUserPartnerOperationsAsync>d__7.MoveNext() in C:\Users\salman\Desktop\SAM - Azure\Partner-Center-DotNet-Samples-dev-samples-update\secure-app-model\keyvault\CSPApplication\Program.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CPVApplication.Program.<Run>d__3.MoveNext() in C:\Users\salman\Desktop\SAM - Azure\Partner-Center-DotNet-Samples-dev-samples-update\secure-app-model\keyvault\CSPApplication\Program.cs:line 45
Console.ReadLine();

**Comment by isaiahwilliams** [comment]
Hi @SalmanMukhtar, 

We are working to include additional documentation for these samples. Currently we only have documentation available through [Yammer](https://www.yammer.com/cloudpartnercommunity). To better determine what is causing this can you provide the following information 

1. Have you deployed an instance of Azure Key Vault?
2. Did you configure the access policies to allow the application access to the instance of Azure Key Vault?
3. Did you walk through the partner consent sample first? 

Please let us know the answers to the questions above, so we can better determine what is causing this issue.

**Comment by SalmanMukhtar** [comment]
Hi @isaiahwilliams 

I worked on first 2 points but not the third one. So i will check that.

Regards,
Salman

**Comment by isaiahwilliams** [comment]
Hi @SalmanMukhtar, 

The NotFound error is usually an indicator that there is not a secret in the instance of Azure Key Vault that matches what you are requesting. Can you confirm that there is a secret with the name of what you are requesting in the instance of Azure Key Vault?

**Comment by isaiahwilliams** [comment]
If you are still experincing this issue please feel free to re-open this issue.

**Comment by lukasz-rakowski** [comment]
I have the same issue. Is someone who can help me with this?

**Comment by rajarajanj** [comment]
I am also facing the same issue. An instance of secret exists in Azure key vault. But, still I get this exception. Is there an resolution for this issue?

**Comment by rajarajanj** [comment]
> Hi @SalmanMukhtar,
> 
> The NotFound error is usually an indicator that there is not a secret in the instance of Azure Key Vault that matches what you are requesting. Can you confirm that there is a secret with the name of what you are requesting in the instance of Azure Key Vault?

In my case, yes, the secret exists in the instance of Azure Key Vault. When I connect to the secret from my local machine, it works. But, when the call originates from Odata Service deployed on Kubernetes cluster to Key Vault, I get this exception.

**Comment by SalmanMukhtar** [comment]
Hi,

I am not sure about the right solution but this worked for me.
I removed the secret from the key vault and generated a new one with the consent app and it worked.

**Comment by AshleyYang25** [comment]
@rajarajanj Hello, did you resolve the problem? I met the same problem.

**Comment by rajarajanj** [comment]
> @rajarajanj Hello, did you resolve the problem? I met the same problem.

Hi @AshleyYang25 

It was due to wrong Key-Vault name I had given. After correcting the KV name, it worked fine for me.

**Comment by AshleyYang25** [comment]
> > @rajarajanj Hello, did you resolve the problem? I met the same problem.
> 
> Hi @AshleyYang25
> 
> It was due to wrong Key-Vault name I had given. After correcting the KV name, it worked fine for me.

@rajarajanj Thanks, I made the same mistake.
